import Head from 'next/head'
// import styles from '../../styles/home/home.module.css'
import Navbar from '../common/navbar/navbar'
import MainLayout from '../layouts/mainLayout'

const DefaultLayout = ({ children }) => {
  return (
    <div className="flex h-screen flex-col justify-between">
      <Head>
        <title>Poulailler 3000</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="">
        <Navbar></Navbar>
      </header>
      <MainLayout>{children}</MainLayout>

      {/* <footer className={styles.footer}>
        <p>Je suis un footer</p>
      </footer> */}
    </div>
  )
}

export default DefaultLayout
